---
language: java
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
notifications:
  email:
    recipients:
      - whatsyourfavouritehummingnoise@gmail.com
    on_success: change
    on_failure: change
...
